import { Metadata } from "next";

// global css
import "./styles/global.css";

// components
import Header from "./components/header";

export const metadata: Metadata = {
  title: {
    template: "%s | NY Times Books",
    default: "NY Times Books",
  },
  description: "NY Times Best Sellers App Generated by Next.js 14",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
