import { Metadata } from "next";

// global css
import "./styles/global.css";
import { Work_Sans } from "next/font/google";

// components
import Header from "./components/header";

const WorkSans = Work_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | NY Times Books",
    default: "NY Times Books",
  },
  description: "NY Times Best Sellers App Generated by Next.js 14",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={WorkSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
